import type { AppSettingValue } from "@workspace/db";

export type RuntimeSettingType = "boolean" | "integer" | "string";

export interface RuntimeSettingDefinition {
	defaultValue: AppSettingValue;
	description: string;
	envName?: string;
	group: "features" | "hostify" | "hostkit";
	key: string;
	label: string;
	max?: number;
	min?: number;
	type: RuntimeSettingType;
}

export const runtimeSettingDefinitions = [
	{
		defaultValue: true,
		description: "Create live Hostify reservations during checkout.",
		envName: "HOSTIFY_BOOKINGS_ENABLED",
		group: "features",
		key: "features.hostifyBookingsEnabled",
		label: "Hostify bookings",
		type: "boolean",
	},
	{
		defaultValue: true,
		description: "Refund automatically when a paid order cannot be confirmed.",
		envName: "COMMERCE_AUTO_REFUND",
		group: "features",
		key: "features.commerceAutoRefund",
		label: "Automatic refunds",
		type: "boolean",
	},
	{
		defaultValue: false,
		description: "Allow operators to issue fiscal documents in Hostkit.",
		envName: "HOSTKIT_INVOICING_ENABLED",
		group: "features",
		key: "features.hostkitInvoicingEnabled",
		label: "Hostkit invoicing",
		type: "boolean",
	},
	{
		defaultValue: false,
		description: "Submit SIBA bulletins after guest data validates in Hostkit.",
		envName: "HOSTKIT_SIBA_SEND_ENABLED",
		group: "features",
		key: "features.hostkitSibaSendEnabled",
		label: "Send SIBA",
		type: "boolean",
	},
	{
		defaultValue: true,
		description:
			"Use the listing localization model during Hostify listing sync.",
		envName: "LISTING_LLM_ENABLED",
		group: "features",
		key: "features.listingLlmEnabled",
		label: "Listing AI processing",
		type: "boolean",
	},
	{
		defaultValue: "default",
		description:
			"Hostify account scope used by cached listings, pricing and reviews.",
		envName: "HOSTIFY_ACCOUNT_ID",
		group: "hostify",
		key: "hostify.accountId",
		label: "Hostify account id",
		type: "string",
	},
	{
		defaultValue: 10,
		description:
			"Number of listings processed in one incremental listing sync pass.",
		envName: "HOSTIFY_LISTING_INCREMENTAL_BATCH_SIZE",
		group: "hostify",
		key: "hostify.listingIncrementalBatchSize",
		label: "Listing batch size",
		max: 100,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 24,
		description: "Hours between regular Hostify listing sync attempts.",
		envName: "HOSTIFY_LISTING_SYNC_INTERVAL_HOURS",
		group: "hostify",
		key: "hostify.listingSyncIntervalHours",
		label: "Listing sync interval",
		max: 720,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 10,
		description:
			"Minutes before an abandoned listing sync lease can be retried.",
		envName: "HOSTIFY_LISTING_SYNC_LEASE_MINUTES",
		group: "hostify",
		key: "hostify.listingSyncLeaseMinutes",
		label: "Listing lease minutes",
		max: 120,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 50,
		description: "Maximum Hostify pages read during a listing sync.",
		envName: "HOSTIFY_LISTING_SYNC_MAX_PAGES",
		group: "hostify",
		key: "hostify.listingSyncMaxPages",
		label: "Listing max pages",
		max: 500,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 50,
		description: "Listings requested from Hostify per listing-sync page.",
		envName: "HOSTIFY_LISTING_SYNC_PER_PAGE",
		group: "hostify",
		key: "hostify.listingSyncPerPage",
		label: "Listing page size",
		max: 100,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 24,
		description: "Hours before cached listing content is considered stale.",
		envName: "HOSTIFY_LISTING_STALE_AFTER_HOURS",
		group: "hostify",
		key: "hostify.listingStaleAfterHours",
		label: "Listing stale hours",
		max: 720,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 10,
		description: "Number of listings processed in one review sync pass.",
		envName: "HOSTIFY_REVIEW_SYNC_BATCH_SIZE",
		group: "hostify",
		key: "hostify.reviewSyncBatchSize",
		label: "Review batch size",
		max: 100,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 24,
		description: "Hours between regular Hostify review sync attempts.",
		envName: "HOSTIFY_REVIEW_SYNC_INTERVAL_HOURS",
		group: "hostify",
		key: "hostify.reviewSyncIntervalHours",
		label: "Review sync interval",
		max: 720,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 10,
		description:
			"Minutes before an abandoned review sync lease can be retried.",
		envName: "HOSTIFY_REVIEW_SYNC_LEASE_MINUTES",
		group: "hostify",
		key: "hostify.reviewSyncLeaseMinutes",
		label: "Review lease minutes",
		max: 120,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 50,
		description: "Maximum Hostify pages read during a review sync.",
		envName: "HOSTIFY_REVIEW_SYNC_MAX_PAGES",
		group: "hostify",
		key: "hostify.reviewSyncMaxPages",
		label: "Review max pages",
		max: 500,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: "EUR",
		description: "Currency used for accommodation pricing and order creation.",
		envName: "ACCOMMODATION_CURRENCY",
		group: "hostify",
		key: "accommodations.currency",
		label: "Accommodation currency",
		type: "string",
	},
	{
		defaultValue: 10,
		description: "Listings processed in one nightly price sync pass.",
		envName: "ACCOMMODATION_NIGHTLY_PRICE_SYNC_BATCH_SIZE",
		group: "hostify",
		key: "accommodations.nightlyPriceSyncBatchSize",
		label: "Price batch size",
		max: 100,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 540,
		description: "Future days fetched during nightly price sync.",
		envName: "ACCOMMODATION_NIGHTLY_PRICE_SYNC_DAYS",
		group: "hostify",
		key: "accommodations.nightlyPriceSyncDays",
		label: "Price sync days",
		max: 730,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 24,
		description: "Hours between regular nightly price sync attempts.",
		envName: "ACCOMMODATION_NIGHTLY_PRICE_SYNC_INTERVAL_HOURS",
		group: "hostify",
		key: "accommodations.nightlyPriceSyncIntervalHours",
		label: "Price sync interval",
		max: 720,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 10,
		description:
			"Minutes before an abandoned nightly price sync lease can retry.",
		envName: "ACCOMMODATION_NIGHTLY_PRICE_SYNC_LEASE_MINUTES",
		group: "hostify",
		key: "accommodations.nightlyPriceSyncLeaseMinutes",
		label: "Price lease minutes",
		max: 120,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 50,
		description: "Maximum Hostify pages read during nightly price sync.",
		envName: "ACCOMMODATION_NIGHTLY_PRICE_SYNC_MAX_PAGES",
		group: "hostify",
		key: "accommodations.nightlyPriceSyncMaxPages",
		label: "Price max pages",
		max: 500,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: 100,
		description: "Maximum listings processed by one nightly price sync run.",
		envName: "ACCOMMODATION_NIGHTLY_PRICE_SYNC_MAX_LISTINGS",
		group: "hostify",
		key: "accommodations.nightlyPriceSyncMaxListings",
		label: "Price max listings",
		max: 500,
		min: 1,
		type: "integer",
	},
	{
		defaultValue: "gpt-5.5",
		description: "Model used to prepare multilingual listing content.",
		envName: "OPENAI_LISTING_MODEL",
		group: "hostify",
		key: "listing.openaiModel",
		label: "Listing AI model",
		type: "string",
	},
	{
		defaultValue: "https://app.hostkit.pt/api/",
		description: "Hostkit API base URL. Must remain HTTPS.",
		envName: "HOSTKIT_BASE_URL",
		group: "hostkit",
		key: "hostkit.baseUrl",
		label: "Hostkit base URL",
		type: "string",
	},
	{
		defaultValue: "",
		description: "Optional Hostkit account uid forwarded with each request.",
		envName: "HOSTKIT_UID",
		group: "hostkit",
		key: "hostkit.uid",
		label: "Hostkit uid",
		type: "string",
	},
	{
		defaultValue: 2,
		description: "Read retries for transient Hostkit failures.",
		envName: "HOSTKIT_MAX_READ_RETRIES",
		group: "hostkit",
		key: "hostkit.maxReadRetries",
		label: "Hostkit read retries",
		max: 5,
		min: 0,
		type: "integer",
	},
	{
		defaultValue: 250,
		description: "Initial Hostkit retry delay in milliseconds.",
		envName: "HOSTKIT_RETRY_DELAY_MS",
		group: "hostkit",
		key: "hostkit.retryDelayMs",
		label: "Hostkit retry delay",
		max: 30_000,
		min: 0,
		type: "integer",
	},
	{
		defaultValue: 15_000,
		description: "Hostkit request timeout in milliseconds.",
		envName: "HOSTKIT_TIMEOUT_MS",
		group: "hostkit",
		key: "hostkit.timeoutMs",
		label: "Hostkit timeout",
		max: 120_000,
		min: 1,
		type: "integer",
	},
] as const satisfies readonly RuntimeSettingDefinition[];

export type RuntimeSettingKey =
	(typeof runtimeSettingDefinitions)[number]["key"];

export const runtimeSettingDefinitionByKey = new Map(
	runtimeSettingDefinitions.map((definition) => [definition.key, definition]),
);
