import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const distDir = join(root, "dist");
const outDir = join(root, "generated");

interface TemplateEntry {
	name: string;
	htmlFile: string;
	textFile: string;
	exportName: string;
}

const templates: TemplateEntry[] = [
	{
		name: "verification",
		htmlFile: "verification.html",
		textFile: "verification.txt",
		exportName: "verification",
	},
	{
		name: "password-reset",
		htmlFile: "password-reset.html",
		textFile: "password-reset.txt",
		exportName: "passwordReset",
	},
	{
		name: "order-confirmation",
		htmlFile: "order-confirmation.html",
		textFile: "order-confirmation.txt",
		exportName: "orderConfirmation",
	},
];

function loadFile(filePath: string): string | null {
	const abs = join(distDir, filePath);
	if (!existsSync(abs)) return null;
	return readFileSync(abs, "utf-8");
}

function normalizeGeneratedText(text: string): string {
	return `${text
		.replace(/\u200d/g, "")
		.replace(/[ \t]+\r?\n/g, "\n")
		.replace(/\n{3,}/g, "\n\n")
		.trim()}\n`;
}

const lines: string[] = [];
lines.push("// Auto-generated by scripts/generate-templates.ts. Do not edit.");
lines.push("");

for (const tpl of templates) {
	const html = loadFile(tpl.htmlFile);
	if (html !== null) {
		lines.push(
			`export const ${tpl.exportName}Html: string = ${JSON.stringify(html)};`,
		);
	} else {
		lines.push(
			`// ${tpl.htmlFile} not found - ${tpl.exportName}Html unavailable`,
		);
	}

	const text = loadFile(tpl.textFile);
	if (text !== null) {
		const normalizedText = normalizeGeneratedText(text);
		writeFileSync(join(distDir, tpl.textFile), normalizedText, "utf-8");
		lines.push(
			`export const ${tpl.exportName}Text: string = ${JSON.stringify(normalizedText)};`,
		);
	} else {
		lines.push(
			`// ${tpl.textFile} not found - ${tpl.exportName}Text unavailable`,
		);
	}

	lines.push("");
}

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "templates.ts"), lines.join("\n"), "utf-8");

console.log(
	`Generated ${join(outDir, "templates.ts")} with ${templates.length} template(s).`,
);
