export const AMENITY_ICON_SET = "fa6" as const;

export const AMENITY_ICON_NAMES = [
	"FaBath",
	"FaBed",
	"FaBellConcierge",
	"FaBicycle",
	"FaBookOpen",
	"FaBriefcase",
	"FaCar",
	"FaChargingStation",
	"FaClock",
	"FaDog",
	"FaDumbbell",
	"FaElevator",
	"FaFan",
	"FaFireExtinguisher",
	"FaGamepad",
	"FaHotTubPerson",
	"FaHouseSignal",
	"FaKey",
	"FaKitchenSet",
	"FaLock",
	"FaMoon",
	"FaMountainSun",
	"FaMugSaucer",
	"FaPersonSkiing",
	"FaPersonSwimming",
	"FaPlug",
	"FaShieldHeart",
	"FaShower",
	"FaSnowflake",
	"FaSoap",
	"FaSquareParking",
	"FaSuitcaseMedical",
	"FaSun",
	"FaTemperatureArrowUp",
	"FaTree",
	"FaTv",
	"FaUmbrellaBeach",
	"FaUtensils",
	"FaVault",
	"FaWater",
	"FaWaterLadder",
	"FaWheelchair",
	"FaWifi",
	"FaWineGlass",
] as const;

export type AmenityIconName = (typeof AMENITY_ICON_NAMES)[number];

const DEFAULT_ICON: AmenityIconName = "FaBellConcierge";

const KEYWORD_ICONS: ReadonlyArray<[RegExp, AmenityIconName]> = [
	[/wi-?fi|internet/i, "FaWifi"],
	[/parking|garage/i, "FaSquareParking"],
	[/pool|swim/i, "FaWaterLadder"],
	[/hot.?tub|jacuzzi|spa/i, "FaHotTubPerson"],
	[/kitchen|oven|stove|cook/i, "FaKitchenSet"],
	[/air.?conditioning|a\/c|cooling/i, "FaSnowflake"],
	[/heat|heating|fireplace/i, "FaTemperatureArrowUp"],
	[/tv|television/i, "FaTv"],
	[/washer|dryer|laundry/i, "FaSoap"],
	[/pet|dog/i, "FaDog"],
	[/baby|crib|kid|child/i, "FaBed"],
	[/gym|fitness/i, "FaDumbbell"],
	[/beach/i, "FaUmbrellaBeach"],
	[/ski/i, "FaPersonSkiing"],
	[/bike|bicycle/i, "FaBicycle"],
	[/accessible|wheelchair/i, "FaWheelchair"],
	[/elevator|lift/i, "FaElevator"],
	[/car|vehicle/i, "FaCar"],
	[/ev|charging/i, "FaChargingStation"],
	[/safe|vault/i, "FaVault"],
	[/security/i, "FaShieldHeart"],
	[/first.?aid|medical/i, "FaSuitcaseMedical"],
	[/shower/i, "FaShower"],
	[/bath/i, "FaBath"],
	[/wine|bar/i, "FaWineGlass"],
	[/coffee|tea/i, "FaMugSaucer"],
	[/workspace|desk|laptop/i, "FaBriefcase"],
	[/guide|manual|book/i, "FaBookOpen"],
	[/view|mountain/i, "FaMountainSun"],
	[/garden|tree/i, "FaTree"],
	[/water|river|sea|ocean/i, "FaWater"],
	[/key|self.?check/i, "FaKey"],
	[/lock/i, "FaLock"],
	[/concierge|service/i, "FaBellConcierge"],
	[/game/i, "FaGamepad"],
	[/fan/i, "FaFan"],
	[/plug|outlet/i, "FaPlug"],
	[/breakfast|restaurant|dining|utensil/i, "FaUtensils"],
];

export function pickAmenityIcon(label: string): AmenityIconName {
	return (
		KEYWORD_ICONS.find(([pattern]) => pattern.test(label))?.[1] ?? DEFAULT_ICON
	);
}
