/**
 * Generates `src/listing-cache/amenity-catalog.ts` from the Hostify amenity
 * list captured in `docs/hostify/amenities.json` (id -> English label). Each
 * amenity is assigned a stable Font Awesome 6 icon via the keyword heuristic in
 * `amenity-icons.ts`, with per-id corrections applied from
 * `AMENITY_ICON_OVERRIDES`.
 *
 * Run after editing the amenity list or the overrides:
 *   bun run packages/core/scripts/generate-amenity-catalog.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	AMENITY_ICON_OVERRIDES,
	type AmenityIconName,
	pickAmenityIcon,
} from "../src/listing-cache/amenity-icons";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const sourcePath = join(repoRoot, "docs", "hostify", "amenities.json");
const outPath = join(here, "..", "src", "listing-cache", "amenity-catalog.ts");

const raw = JSON.parse(readFileSync(sourcePath, "utf8")) as Record<
	string,
	string
>;

interface Entry {
	icon: AmenityIconName;
	id: string;
	label: string;
}

/**
 * Decodes common HTML entities in amenity labels.
 */
function decodeHtmlEntities(text: string): string {
	return text
		.replace(/&amp;/g, "&")
		.replace(/&lt;/g, "<")
		.replace(/&gt;/g, ">")
		.replace(/&quot;/g, '"')
		.replace(/&#39;/g, "'")
		.replace(/&apos;/g, "'");
}

const entries: Entry[] = Object.entries(raw)
	.map(([id, label]) => ({
		icon: AMENITY_ICON_OVERRIDES[id] ?? pickAmenityIcon(label),
		id,
		label: decodeHtmlEntities(label).trim(),
	}))
	.filter((entry) => entry.id.length > 0 && entry.label.length > 0)
	.sort((a, b) => Number(a.id) - Number(b.id));

const body = entries
	.map(
		(entry) =>
			`\t"${entry.id}": { icon: "${entry.icon}", label: ${JSON.stringify(entry.label)} },`,
	)
	.join("\n");

const file = `// GENERATED by scripts/generate-amenity-catalog.ts. Do not edit by hand.
// Source: docs/hostify/amenities.json. Icon assignment: amenity-icons.ts
// (keyword heuristic + AMENITY_ICON_OVERRIDES). Re-run the script to update.
import type { AmenityIconName } from "./amenity-icons";

export interface AmenityCatalogEntry {
	icon: AmenityIconName;
	label: string;
}

/** Hostify amenity id -> canonical icon + English label. */
export const HOSTIFY_AMENITY_CATALOG: Readonly<
	Record<string, AmenityCatalogEntry>
> = {
${body}
};
`;

writeFileSync(outPath, file, "utf8");

const counts = new Map<string, number>();
for (const entry of entries) {
	counts.set(entry.icon, (counts.get(entry.icon) ?? 0) + 1);
}
const defaults = entries.filter((entry) => entry.icon === "FaBellConcierge");

console.log(`Wrote ${entries.length} amenities to ${outPath}`);
console.log(`Distinct icons used: ${counts.size}`);
console.log(`Fell back to default (FaBellConcierge): ${defaults.length}`);
for (const entry of defaults) {
	console.log(`  ${entry.id}\t${entry.label}`);
}
