const HOSTIFY_PROPERTY_TYPE_LABELS = new Map<string, string>([
	["1", "Apartment"],
	["2", "Bungalow"],
	["3", "Cabin"],
	["4", "Condominium"],
	["5", "Guesthouse"],
	["6", "House"],
	["7", "Guest Suite"],
	["8", "Townhouse"],
	["9", "Vacation Home"],
	["10", "Boutique Hotel"],
	["11", "Nature Lodge"],
	["12", "Hostel"],
	["13", "Chalet"],
	["14", "Dorm"],
	["15", "Villa"],
	["16", "Other"],
	["17", "Bed and Breakfast"],
	["18", "Studio"],
	["19", "Hotel"],
	["20", "Resort"],
	["21", "Castle"],
	["22", "Aparthotel"],
	["23", "Boat"],
	["24", "Cottage"],
	["25", "Camping"],
	["26", "Serviced Apartment"],
	["27", "Loft"],
	["28", "Hut"],
	["29", "Barn"],
	["30", "Cave"],
	["31", "Dome House"],
	["32", "Earthhouse"],
	["33", "Farm Stay"],
	["34", "Holiday Park"],
	["35", "Houseboat"],
	["36", "Igloo"],
	["37", "Island"],
	["38", "Kezhan"],
	["39", "Lighthouse"],
	["40", "Plane"],
	["41", "Ranch"],
	["42", "Religious Building"],
	["43", "Riad"],
	["44", "RV"],
	["45", "Shipping Container"],
	["46", "Tent"],
	["47", "Tiny House"],
	["48", "Tipi"],
	["49", "Tower"],
	["50", "Train"],
	["51", "Treehouse"],
	["52", "Windmill"],
	["53", "Yurt"],
]);

export function hostifyPropertyTypeLabel(value: string | null): string | null {
	return value ? (HOSTIFY_PROPERTY_TYPE_LABELS.get(value) ?? null) : null;
}
